name: Publish Docker image
# TODO 当snell官方仓库更新版本时，自动触发构建
# TODO 利用docker tower？自动更新vps上的container
on:
  # schedule:
  #   - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - '**'  
      - '!main'  # exclude main git
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

# 定义全局环境变量
env:
  SNELL_VERSION: "2.0.5"
  GLIBC_VERSION: "2.34-r0"
  SERVER_PORT: "32910"
  IMAGE_NAME: "snell"
  
jobs:
  push_to_registries:
    name: Push docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # 设置 QEMU, 后面 docker buildx 依赖此.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      # 设置 Docker buildx, 方便构建 Multi platform 镜像
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
      # 打印支持构建的平台 
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Docker Hub
        # 只有当github事件不是pr时才会登陆执行docker login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v3.6.1
        with:
          images: |
            flygar/${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository }}
          #  将分支名 v1.x.x 转换为镜像tag 1.x.x 的形式。参考：https://github.com/marketplace/actions/docker-metadata-action#typesemver
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          # 只有当github的事件不是pr时才会执行push
          push: ${{ github.event_name != 'pull_request' }}
          # 生成多平台镜像
          platforms: |
            linux/amd64
          # TODO 需要修改新增下载arm64架构下的snell的dockerfile。并在当前action新增变量，指定具体的dockerfile。后面树莓派做透明网关可能会用到树莓派架构的snell。
          # linux/arm64 
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SNELL_VERSION=${{ env.SNELL_VERSION }}
            GLIBC_VERSION=${{ env.GLIBC_VERSION }}
            SERVER_PORT=${{ env.SERVER_PORT }}
